urlhunter/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from urlhunter.forms import LoginForm, RegisterForm
from urlhunter.models import User
from urlhunter.extensions import db
from flask_login import current_user, login_user, logout_user


bp = Blueprint('auth', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            flash('该用户不存在！', 'danger')
        elif not user.check_password(password=form.password.data):
            flash('密码错误！', 'danger')
        else:
            login_user(user, remember=form.remember_me.data)
            return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('auth/login.html', form=form)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('注册成功！', 'success')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form)


@bp.route('/logout')
def log_out():
    logout_user()
    return redirect(url_for('main.index'))

urlhunter/blueprints/main.py
import requests
from more_itertools import flatten
from flask import Blueprint, render_template, flash, redirect, url_for, request, current_app, Markup
from flask_login import login_required, current_user
from urlhunter.forms import URLForm, RegexForm
from urlhunter.utils import links
from urlhunter.models import Url, Regex
from urlhunter.extensions import db

bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    return render_template('main/index.html')


@bp.route('/extract', methods=['GET', 'POST'])
@login_required
def extract():
    form = URLForm()
    extracted_urls = None
    if form.validate_on_submit():
        try:
            if Url.query.count() > current_app.config['URL_LIMIT']:
                raise Exception(f"URL超限了！请先清空！[{Url.query.count()}/{current_app.config['URL_LIMIT']}]")
            urls = form.urls.data.split('\n')
            headers = {
                'User-Agent':
                'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36'
            }
            responses = [
                requests.get(url.strip(), headers=headers) for url in urls
            ]
            if form.search.data:
                if form.use_regex.data is True:
                    extracted_urls = [
                        links(resp, pattern=form.search.data)
                        for resp in responses
                    ]
                else:
                    extracted_urls = [
                        links(resp, search=form.search.data)
                        for resp in responses
                    ]
            else:
                extracted_urls = [links(resp) for resp in responses]
            extracted_urls = list(flatten(extracted_urls))
            if len(extracted_urls) == 0:
                raise Exception('啊嘞？啥都没捕捉到哦U_U')
        except Exception as e:
            flash(e, 'danger')
        else:
            flash(
                Markup(
                    f"成功捕获到{len(extracted_urls)}条url XD <a href={url_for('main.show_urls')}>立即查看</a>"
                ), 'success')
            for extracted_url in extracted_urls:
                if not Url.query.filter_by(body=extracted_url).first():
                    url = Url(
                        body=extracted_url,
                        owner=current_user._get_current_object())
                    db.session.add(url)
            db.session.commit()
            return redirect(url_for('main.extract'))
    form.urls.data = request.args.get('urls')
    form.search.data = request.args.get('search')
    form.use_regex.data = bool(request.args.get('use_regex'))
    return render_template(
        'main/extract.html', form=form, extracted_urls=extracted_urls)


@bp.route('/urls')
@login_required
def show_urls():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['URL_PER_PAGE']
    current_user_urls = Url.query.with_parent(current_user)
    pagination = current_user_urls.order_by(
        Url.timestamp.desc()).paginate(page, per_page)
    urls = pagination.items
    outputs = '\n'.join([url.body for url in current_user_urls.all()])
    exclude_strings = request.args.get('exclude')
    if exclude_strings:
        urls, outputs = exclude_urls(exclude_strings, urls, current_user_urls)
    return render_template('main/urls.html', urls=urls, pagination=pagination, outputs=outputs)


@bp.route('/urls/delete/all', methods=['POST'])
@login_required
def delete_urls():
    urls = Url.query.with_parent(current_user._get_current_object()).all()
    db.session.execute('delete from url')
    db.session.commit()
    flash('操作成功！', 'success')
    return redirect(url_for('main.show_urls'))


@bp.route('/urls/search')
@login_required
def search_urls():
    q = request.args.get('q', '')
    if q == '':
        flash('请输入要搜索的URL', 'warning')
        return redirect(url_for('main.show_urls'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['SEARCH_PER_PAGE']
    searched_urls = Url.query.with_parent(current_user).filter(Url.body.ilike(f'%{q}%'))
    pagination = searched_urls.paginate(page, per_page)
    results = pagination.items
    outputs = '\n'.join([url.body for url in searched_urls.all()])
    exclude_strings = request.args.get('exclude')
    if exclude_strings:
        results, outputs = exclude_urls(exclude_strings, results, searched_urls)
    return render_template('main/search.html', pagination=pagination, results=results, q=q, outputs=outputs)


@bp.route('/regexs')
@login_required
def show_regexs():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['REGEX_PER_PAGE']
    pagination = Regex.query.with_parent(current_user).paginate(page, per_page)
    regexs = pagination.items
    return render_template('main/regexs.html', regexs=regexs, pagination=pagination)


@bp.route('/regexs/upload', methods=['GET', 'POST'])
@login_required
def upload_regex():
    form = RegexForm()
    if form.validate_on_submit():
        name = form.name.data
        site = form.site.data
        body = form.body.data
        regex = Regex(name=name, site=site, body=body, author=current_user._get_current_object())
        db.session.add(regex)
        db.session.commit()
        flash('添加成功！', 'success')
        return redirect(url_for('main.show_regexs'))
    return render_template('main/upload.html', form=form)


@bp.route('/help')
def show_help():
    return render_template('main/help.html')


@bp.app_template_global()
def exclude_urls(exclude_strings, paginated_urls, all_urls):
    exclude_strings = exclude_strings.split(',')
    excluded_paginated_urls = [url for url in paginated_urls if not any(es in url.body for es in exclude_strings)]
    excluded_all_urls = [url for url in all_urls.all() if not any(es in url.body for es in exclude_strings)]
    excluded_outputs = '\n'.join([url.body for url in excluded_all_urls])
    return excluded_paginated_urls, excluded_outputs

urlhunter/blueprints/user.py
from flask import Blueprint, render_template
from urlhunter.models import User

bp = Blueprint('user', __name__)


@bp.route('/<string:username>')
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user/index.html', user=user)

urlhunter/templates/layout.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html>

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} - {{config['SITE_NAME']}}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    {% block styles %}
    {{ bootstrap.load_css() }}
    <link rel="stylesheet" href="https://bootswatch.com/4/simplex/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% endblock styles %}
    {% endblock head %}
</head>

<body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{url_for('main.index')}}">
                <img src="{{ url_for('static', filename='favicon.ico') }}" height="32" width="32">
                &nbsp;{{ config['SITE_NAME'] }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="nav navbar-nav ml-auto">
                    {{render_nav_item('main.show_help', '使用说明')}}
                    {{render_nav_item('main.extract', '捕获URL')}}
                    {{render_nav_item('main.show_urls', '我的URL')}}
                    {{render_nav_item('main.show_regexs', '我的正则')}}
                    {{render_nav_item('main.upload_regex', '自定义正则')}}
                    {% if current_user.is_anonymous %}
                    {{render_nav_item('auth.login', '登录')}}
                    {% else %}
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{{ current_user.avatar(22) }}">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                            <h6 class="dropdown-header">{{ current_user.username}}</h6>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('user.index', username=current_user.username) }}"><span
                                    class="fa fa-user"></span>&nbsp;我的主页</a>
                            <a class="dropdown-item" href="{{ url_for('auth.log_out') }}"><span class="fa fa-power-off"></span>&nbsp;登出</a>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endblock nav %}
    <main class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-dismissable alert-{{ category }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
        {% block footer %}
        <footer>
            <p class="float-left">
                <small>&copy;
                    Made by <a href="https://github.com/{{config['GITHUB_USERNAME']}}" target="_blank">{{config['GITHUB_USERNAME']}}</a>
                    with <span class="fa fa-heart"></span>
                </small>
            </p>
            <p class="float-right">
                <small><a href="mailto:{{ config['EMAIL'] }}">Contact</a></small>
            </p>
        </footer>
        {% endblock footer %}
    </main>
    {% block scripts %}
    {{ bootstrap.load_js() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-cn') }}
    <script src="{{url_for('static', filename='js/script.js')}}"></script>
    {% endblock %}
</body>

</html>

urlhunter/templates/macros.html
{% from "bootstrap/pagination.html" import render_pagination %}
{% macro urllist(urls, pagination) %}
{% if urls %}
    <table class="table table-striped table-inverse table-responsive">
        <thead class="thead-inverse">
            <tr>
                <th>URL</th>
                <th>时间</th>
            </tr>
            </thead>
            <tbody>
                {% for url in urls %}
                <tr>
                    <td scope="row"><a href="{{url.body}}" target="_blank">{{url.body|truncate(60)}}</a></td>
                    <td>{{moment(url.timestamp).format('LLL')}}</td>
                </tr>
                {% endfor %}
            </tbody>
    </table>
    {% if pagination and pagination.pages > 1 %}
        {{render_pagination(pagination)}}
    {% endif %}
{% else %}
    <div class="tip">还没有URL哦，快去<a href="{{url_for('main.extract')}}">捕获</a>它们吧！</div>
{% endif %}
{% endmacro %}

{% macro regexlist(regexs, pagination) %}
{% if regexs %}
<ul class="list-group">
    {% for regex in regexs %}
    <li class="list-group-item">
        {% set site = regex.site %}
        {% set name = regex.name %}
        {% set body = regex.body %}
        <a type="button" class="btn btn-primary" href={{site}} target="_blank">{{name}}</a>&nbsp;&nbsp;
        {{body}}
        <span class="float-right">
            <a class="btn btn-info" href="{{url_for('main.extract', urls=site, search=body, use_regex=True)}}">使用</a>
            </div>
    </li>
    {% endfor %}
</ul>
{% if pagination and pagination.pages > 1 %}
<div class="page-footer">
{{render_pagination(pagination)}}
</div>
{% endif %}
{% else %}
<div class="tip">
    你还没有自定义的正则，快去<a href="{{url_for('main.upload_regex')}}">定义</a>吧！
</div>
{% endif %}
{% endmacro %}

{% macro output_urls(outputs) %}
{% if outputs %}
<!-- Button trigger modal -->
<button type="button" class="list-group-item list-group-item-action" data-toggle="modal" data-target="#outputModal">
    一键导出URL
</button>
<!-- Output Modal -->
<div class="modal fade" id="outputModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">尽情享用吧:D</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <textarea class="form-control" rows="10">{{outputs}}</textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endmacro %}

{% macro search_form() %}
<form action="{{url_for('main.search_urls')}}" method="get">
    <div class="input-group">
        <input type="text" class="form-control" aria-label="url search" name="q" placeholder="查找URL" value="{{request.args.get('q', '')}}">
        <div class="input-group-append">
            <button type="submit" class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
            </button>
        </div>
    </div>
</form>
{% endmacro %}

{% macro exclude_form(endpoint) %}
<form action="{{url_for(endpoint)}}" method="get">
    <div class="input-group">
        {% if endpoint == 'main.search_urls' %}
        <input type="text" name="q" value="{{request.args.get('q', '')}}" style="display: none;">
        {% endif %}
        <textarea class="form-control" name="exclude" rows="3" placeholder="想排除的字段，用英文逗号分隔">{{request.args.get('exclude', '')}}</textarea>
        <div class="input-group-append">
            <button type="submit" class="input-group-text">
                <i class="fa fa-filter" aria-hidden="true"></i>
            </button>
        </div>
    </div>
</form>
{% endmacro %}