urlhunter/blueprints/main.py
import requests
from more_itertools import flatten
from flask import Blueprint, render_template, flash, redirect, url_for, request, current_app, Markup
from flask_login import login_required, current_user
from urlhunter.forms import URLForm, RegexForm
from urlhunter.utils import links
from urlhunter.models import Url, Regex
from urlhunter.extensions import db

bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    return render_template('main/index.html')


@bp.route('/extract', methods=['GET', 'POST'])
@login_required
def extract():
    form = URLForm()
    extracted_urls = None
    if form.validate_on_submit():
        try:
            if Url.query.count() > current_app.config['URL_LIMIT']:
                raise Exception(f"URL超限了！请先清空！[{Url.query.count()}/{current_app.config['URL_LIMIT']}]")
            urls = form.urls.data.split('\n')
            headers = {
                'User-Agent':
                'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36'
            }
            responses = [
                requests.get(url.strip(), headers=headers) for url in urls
            ]
            if form.search.data:
                if form.use_regex.data is True:
                    extracted_urls = [
                        links(resp, pattern=form.search.data)
                        for resp in responses
                    ]
                else:
                    extracted_urls = [
                        links(resp, search=form.search.data)
                        for resp in responses
                    ]
            else:
                extracted_urls = [links(resp) for resp in responses]
            extracted_urls = list(flatten(extracted_urls))
            if len(extracted_urls) == 0:
                raise Exception('啊嘞？啥都没捕捉到哦U_U')
        except Exception as e:
            flash(e, 'danger')
        else:
            flash(
                Markup(
                    f"成功捕获到{len(extracted_urls)}条url XD <a href={url_for('main.show_urls')}>立即查看</a>"
                ), 'success')
            for extracted_url in extracted_urls:
                if not Url.query.filter_by(body=extracted_url).first():
                    url = Url(
                        body=extracted_url,
                        owner=current_user._get_current_object())
                    db.session.add(url)
            db.session.commit()
            return redirect(url_for('main.extract'))
    form.urls.data = request.args.get('urls')
    form.search.data = request.args.get('search')
    form.use_regex.data = bool(request.args.get('use_regex'))
    return render_template(
        'main/extract.html', form=form, extracted_urls=extracted_urls)


@bp.route('/urls')
@login_required
def show_urls():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['URL_PER_PAGE']
    current_user_urls = Url.query.with_parent(current_user)
    pagination = current_user_urls.order_by(
        Url.timestamp.desc()).paginate(page, per_page)
    urls = pagination.items
    outputs = '\n'.join([url.body for url in current_user_urls.all()])
    exclude_strings = request.args.get('exclude')
    if exclude_strings:
        urls, outputs = exclude_urls(exclude_strings, urls, current_user_urls)
    return render_template('main/urls.html', urls=urls, pagination=pagination, outputs=outputs)


@bp.route('/urls/delete/all', methods=['POST'])
@login_required
def delete_urls():
    urls = Url.query.with_parent(current_user._get_current_object()).all()
    db.session.execute('delete from url')
    db.session.commit()
    flash('操作成功！', 'success')
    return redirect(url_for('main.show_urls'))


@bp.route('/urls/search')
@login_required
def search_urls():
    q = request.args.get('q', '')
    if q == '':
        flash('请输入要搜索的URL', 'warning')
        return redirect(url_for('main.show_urls'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['SEARCH_PER_PAGE']
    searched_urls = Url.query.with_parent(current_user).filter(Url.body.ilike(f'%{q}%'))
    pagination = searched_urls.paginate(page, per_page)
    results = pagination.items
    outputs = '\n'.join([url.body for url in searched_urls.all()])
    exclude_strings = request.args.get('exclude')
    if exclude_strings:
        results, outputs = exclude_urls(exclude_strings, results, searched_urls)
    return render_template('main/search.html', pagination=pagination, results=results, q=q, outputs=outputs)


@bp.route('/regexs')
@login_required
def show_regexs():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['REGEX_PER_PAGE']
    pagination = Regex.query.with_parent(current_user).paginate(page, per_page)
    regexs = pagination.items
    return render_template('main/regexs.html', regexs=regexs, pagination=pagination)


@bp.route('/regexs/upload', methods=['GET', 'POST'])
@login_required
def upload_regex():
    form = RegexForm()
    if form.validate_on_submit():
        name = form.name.data
        site = form.site.data
        body = form.body.data
        regex = Regex(name=name, site=site, body=body, author=current_user._get_current_object())
        db.session.add(regex)
        db.session.commit()
        flash('添加成功！', 'success')
        return redirect(url_for('main.show_regexs'))
    return render_template('main/upload.html', form=form)


@bp.route('/help')
def show_help():
    return render_template('main/help.html')


@bp.app_template_global()
def exclude_urls(exclude_strings, paginated_urls, all_urls):
    exclude_strings = exclude_strings.split(',')
    excluded_paginated_urls = [url for url in paginated_urls if not any(es in url.body for es in exclude_strings)]
    excluded_all_urls = [url for url in all_urls.all() if not any(es in url.body for es in exclude_strings)]
    excluded_outputs = '\n'.join([url.body for url in excluded_all_urls])
    return excluded_paginated_urls, excluded_outputs

urlhunter/templates/main/extract.html
{% extends 'layout.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}捕获URL{% endblock %}

{% block content %}
    {{render_form(form)}}
    <br>
    <p>不会写正则？<a target="_blank" href="https://alphardex.github.io/2018/10/12/%E5%AD%A6%E4%B9%A0%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F/">点此学习</a></p>
{% endblock %}

urlhunter/templates/main/help.html
{% extends 'layout.html' %}

{% block title %}使用说明{% endblock %}

{% block content %}
<div class="page-header">
    <h1>使用说明</h1>
</div>
<h3>
    <a href="{{url_for('main.extract')}}">捕获URL</a>
</h3>
<p>
    有两个输入框，第一个用来输入你想捕获URL的网站来源（可以是多行URL），第二个则是你想搜索过滤的字符
</p>
<p>
    如果想用正则表达式过滤URL，别忘了在<code>使用正则</code>那里打上勾，最后点击<code>提取</code>就可以了
</p>
<h3>
    <a href="{{url_for('main.show_urls')}}">我的URL</a>
</h3>
<p>
    这里展示着你捕获到的URL，上限是10000条，若超过上限则无法继续捕捉URL，需要点击右侧的<code>清空URL</code>
</p>
<p>
    通过<code>查找URL</code>，你可以进一步查找到你想要的URL集合
</p>
<p>
    最后，点击<code>一键导出URL</code>便可将你的URL以纯文本形式导出来，创建一个txt文件，将其复制粘贴进去就行了
</p>
<h3>
    <a href="{{url_for('main.show_regexs')}}">我的正则</a>
</h3>
<p>
    你可以在导航上点击<code>自定义正则</code>来上传自己的正则
</p>
<p>
    点击右侧的<code>使用</code>就可以自动填充好捕获的内容了
</p>
{% endblock %}

urlhunter/templates/main/index.html
{% extends 'layout.html' %}

{% block title %}主页{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <h1 class="display-4">URL乃资源也。</h1>
            <p class="lead">得URL者得天下。</p>
            <p>
                <a class="btn btn-primary btn-lg" role="button" href="{{url_for('main.extract')}}">开始狩猎</a>
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <div class="card-body">
                <h2 class="card-title"><i class="fa fa-link"> 完美捕获</i></h2>
                <p class="card-text">本站将会捕获所有用户输入的URL的网页中包含的每一个URL（图片、外链统统不放过）</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <div class="card-body">
                <h2 class="card-title"><i class="fa fa-filter"> 精准过滤</i></h2>
                <p class="card-text">用户在捕获时可以用字符或者正则来过滤结果，并且能对结果进行搜索，找你想要的。</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <div class="card-body">
                <h2 class="card-title"><i class="fa fa-heart"> 一键导出</i></h2>
                <p class="card-text">没错！只需轻轻一按，你的战利品就会被完整地展现出来，准备好Ctrl+C和Ctrl+V吧。</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

urlhunter/templates/main/regexs.html
{% extends 'layout.html' %}
{% from 'macros.html' import regexlist with context %}

{% block title %}我的正则{% endblock %}

{% block content %}
    {{regexlist(regexs, pagination)}}
{% endblock %}

urlhunter/templates/main/search.html
{% extends 'layout.html' %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% from "macros.html" import urllist with context %}
{% from "macros.html" import search_form %}
{% from "macros.html" import exclude_form with context %}
{% from "macros.html" import output_urls with context %}

{% block title %}搜索结果{% endblock %}

{% block content %}
<div class="row">
    <div class="{% if results %}col-md-8{% else %}col-md-12{% endif %}">
        {{urllist(results, pagination)}}
    </div>
    {% if results %}
    <div class="col-md-4">
        <div class="list-group">
            {{search_form()}}
            {{exclude_form(endpoint="main.search_urls")}}
            {{output_urls(outputs)}}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

urlhunter/templates/main/upload.html
{% extends 'layout.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}自定义正则{% endblock %}

{% block content %}
<div class="page-header">
    <h1>自定义正则</h1>
</div>
{{render_form(form)}}
{% endblock %}

urlhunter/templates/main/urls.html
{% extends 'layout.html' %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% from "macros.html" import urllist with context %}
{% from "macros.html" import search_form %}
{% from "macros.html" import exclude_form with context %}
{% from "macros.html" import output_urls with context %}

{% block title %}我的URL{% endblock %}

{% block content %}
<div class="row">
    <div class="{% if urls %}col-md-8{% else %}col-md-12{% endif %}">
        {{urllist(urls, pagination)}}
    </div>
    {% if urls %}
    <div class="col-md-4">
        <div class="list-group">
            {{search_form()}}
            {{exclude_form(endpoint='main.show_urls')}}
            {{output_urls(outputs)}}
            <button class="list-group-item list-group-item-action" data-toggle="modal" data-target="#delete-modal" data-href="{{url_for('main.delete_urls')}}">清空URL</button>
        </div>
    </div>
    <!-- delete confirm model -->
    <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">删除确认</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    你确定吗？
                </div>
                <div class="modal-footer">
                    <form action="" method="post" class="delete-form">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="button" class="btn btn-default" data-dismiss="modal">算了</button>
                        <button class="btn btn-danger btn-confirm" type="submit">给我删了</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}